### ISSUE TITLE
Click + Drag to reorder

### ISSUE THREAD

**Issue by XCompWiz** [calculist/calculist#16]
I expect this is already on the list (that was not supposed to be a joke... >.<), but I wanted to suggest being able to click and drag the item bullets to be able to arrange them.
As is, clicking them toggles their collapse state, which is handy, but dragging does nothing (aside from text highlighting).

Loving the possibilities and interactions thus far! :D Keep up the fantastic work!  I'm already looking at replacing at least part of my Workflowy usage with this.

**Comment by danallison** [comment]
Thanks! This is on the list of planned features, but it might be a while. In the meantime, you can use these commands and their keyboard shortcuts.

| command | default keyboard shortcut |
|-------------|-------------------------------|
| `move up` | `ctrl + shift + up` |
| `move down` | `ctrl + shift + down` |
| `indent` | `tab` or `ctrl + shift + right` |
| `outdent` | `shift + tab` or `ctrl + shift + left` |

**Comment by danallison** [comment]
This feature has shipped!
