### ISSUE TITLE
Can only have one empty line

### ISSUE THREAD

**Issue by nkallman** [calculist/calculist#18]
I don't know if this behavior is intentional but it seemed odd to me.

I was going to add several blank lines on a new section of a list and it would only allow me to add one blank line (Pressing enter while in a blank line will not create a new line, I can only create a new line by pressing enter on a line with a value in it).

**Comment by danallison** [comment]
Hi @nkallman . Thanks for opening this issue.

The behavior for blank items is intentionally different than items with text. Pressing enter on a blank item should outdent the item. This is consistent with the list item behavior of document editors like Google Docs or Microsoft Word. However, if the item is outdented as far as it can go, then nothing happens, which I agree is odd. It should create new blank items in that case.

For now, if you want to create multiple blank items, there is the `new item` command. The default keyboard shortcut for this is `alt + enter`. Depending on when you signed up, that shortcut may or may not be in you preferences already. If it's not, you can copy-paste into your keyboard shortcuts
```
alt + enter
  new item
```
.

This command/shortcut is also useful if you want to create a new item without splitting the text at the cursor, which is the default behavior when just pressing enter.

**Comment by danallison** [comment]
Ok. I just deployed a fix so that pressing enter on a blank item that cannot outdent creates a new blank item. Let me know if you run into any other strange behaviors like this.
