### ISSUE TITLE
Change  theme doesn't seem to do anything

### ISSUE THREAD

**Issue by evelynmitchell** [calculist/calculist#2]
* change theme "light"
* change theme "dark"
* change theme "sandcastle"

None work.

**Comment by danallison** [comment]
Hmm. What browser are you using?

**Comment by nkallman** [comment]
Same problem for me, 
I'm using Google Chrome Version 53.0.2785.116 (64-bit) on Max OS X 10.11.6 (15G1004)

**Comment by nkallman** [comment]
Ah I see, It only takes effect after a page refresh or after using "goto list ..." 
It doesn't take 'dynamically' and it also won't change if you use the link to the root list on the top bar

**Comment by danallison** [comment]
Ah, are you changing "default theme" in your preferences list? That would require a page refresh, yes. However, if you execute the command `change theme "dark"`, it should take effect immediately.

Does that match what you are seeing?

**Comment by nkallman** [comment]
Yes this matches what I see

**Comment by danallison** [comment]
Ok. I will fix the issue with the link, and also edit the preferences list to clarify that changes require a page refresh in order to take effect.

**Comment by danallison** [comment]
This has been fixed.
