### ISSUE TITLE
"goto list <home list>" leads to 'lists' item disappearing from main section.

### ISSUE THREAD

**Issue by Ginguin** [calculist/calculist#20]
CONTEXT:
The landing page/original list has the original items of
- lists
- stats
- Welcome...

The 'stats' items are populated using the 'lists' items.

BUG:
If the command "goto list 'username'" is entered from another list, the 'lists' item is missing. The URL shows app.calculist.io/'username'/'username'. Removing the second 'username' from the URL or returning to the home page fixes the problem.

The 'stats' items populated using the 'lists' data throws up errors since the 'lists' item is gone.
![image](https://cloud.githubusercontent.com/assets/7907026/21863899/23758302-d7f4-11e6-932a-ce4277e5a2ad.png)

**Comment by danallison** [comment]
Thanks for reporting this. If you go to `app.calculist.io/username/username`, it should now redirect to `app.calculist.io/username` and include the `lists` item.

**Comment by Ginguin** [comment]
Fix confirmed. Thank you for the speedy resolution! I will continue to report bugs as I find them.
