### ISSUE TITLE
Shortcuts incompatible with Google chrome shortcuts

### ISSUE THREAD

**Issue by thomas-dumonet** [calculist/calculist#21]
The following shortcuts don't quite work with chrome shortcuts.

ctrl + shift + delete : open a tab for deletting navigation data.
ctrl + w : closes the current tab on chrome.

I haven't tried them all yet but it's worth checking out, as it may become annoying for chrome users.

**Comment by danallison** [comment]
Hi Thomas. Thanks for opening this issue. Keyboard shortcuts are configurable. Different operating systems and different browsers will inevitably conflict with some of the default shortcuts in Calculist, but you don't have to keep the defaults. Check out [Configuring Preferences](https://github.com/calculist/calculist/wiki/Configuring-Preferences) in the documentation for details. Let me know if you have any other questions.
