### ISSUE TITLE
Math max() and min() don't work

### ISSUE THREAD

**Issue by 1l0** [calculist/calculist#22]

**Comment by danallison** [comment]
Are you sure? Seems to be working for me.

Note that the `max` and `min` functions, unlike the JavaScript `Math.max` and `Math.min`, expect an array of numbers as the argument. So something like

```
top score [=] max($items)
  bob [=] 74
  sally [=] 87
  zoe [=] 98
```

**Comment by 1l0** [comment]
It works! Thank you.
I tried like
```max(x, y, z)```
