### ISSUE TITLE
Cancelling "Open" throws Uncaught Exception error (Windows v0.1.0)

### ISSUE THREAD

**Issue by Ginguin** [calculist/calculist#23]
This is a non-fatal error (everything continues as normal after dismissing the dialog).

If you select File>Open (Ctrl-O) and then Cancel, you get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property '0' of undefined
    at C:\Users\Ginguin\AppData\Local\Programs\CalculistDesktop\resources\app.asar\main.js:88:37
    at Function.wrappedCallback >(C:\Users\Ginguin\AppData\Local\Programs\CalculistDesktop\resources\electron.asar\browser\api\dialog.js:100:14)

```
I will attempt to test this behavior in the linux tonight or tomorrow to see if it affects both versions.

**Comment by Ginguin** [comment]
Confirmed a similar error on Linux version
`Uncaught Exception:
TypeError: Cannot read property '0' of undefined
    at /tmp/.mount_jCO3AI/usr/bin/resources/app.asar/main.js:88:37
    at Function.wrappedCallback (/tmp/.mount_jCO3AI/usr/bin/resources/electron.asar/browser/api/dialog.js:100:14)`

**Comment by danallison** [comment]
Thanks for reporting this. I can reproduce this error on osx as well. It will be addressed in the next version of the desktop app.
