### ISSUE TITLE
How to add new basic functions?

### ISSUE THREAD

**Issue by fiatjaf** [calculist/calculist#25]
I need string manipulation functions (join, split, substr, slice, perhaps regex matching). Is it possible to contribute those, by sending a PR? Should I wait until the project is more mature? Or should I just ask for them and wait for their implementation?

**Comment by danallison** [comment]
`join` and `split` are already available, and I just added `slice`, which will work for both arrays and strings. Note that the first argument to these functions should be the string or array you wish to operate on. For example,
```
joined string [=] join($items, " -> ")
  a
  b
  c
```
would yield `a -> b -> c`.

There are also other string functions `camelCase`,`kebabCase`,`lowerCase`,`upperCase`,`snakeCase`,`startCase`,`toLower`,
`toUpper`,`truncate`,`repeat`,`replace`,`words`,`capitalize`

Pull requests are welcome, though you should be aware that the main repository is in a state of transition while the [working code](https://github.com/calculist/app.calculist.io) is being ported over (which is probably going to take a while). In other words, the code is a bit disorganized at the moment. But don't let that discourage you if you want to open a PR.
