### ISSUE TITLE
Recursive accessor

### ISSUE THREAD

**Issue by sswatson** [calculist/calculist#34]
I'm wondering if there's a recursive version of the column accessor (`data["temperature"]`). I would like to be able to walk the tree of descendants of an item and collect all values associated with a given name. 

I tried to achieve that functionality using the Calculist expression language, but I have the impression that recursive function calls are not supported.

**Comment by danallison** [comment]
Hi @sswatson .

There is a way to construct recursive functions, but it's a bit counter-intuitive, unfortunately. My attempts to implement naturally recursive functions have so far resulted in strange bugs, but I hope to resolve the issues at some point.

For now, the trick is to create partially applied duplicate functions using the `lambda` function, where one function is passed as the argument to the next. The example below demonstrates this.

```
f [:] f, x | x > 100 ? x : f(f, x * x)
rf [=] lambda(f, lambda(f))
result [=] rf(3)
```

I'm not sure how you would use that to collect items in a hierarchy, but there might be other ways to accomplish what you describe. The example below shows how to use the `flatten` and `filter` functions to find all the items with the name "x".

```
root
  first
    attr
      x [=] 1
      x [=] 2
  second
    x [=] 3
get items [=>] items, nm | filter(flatten(items), flow(name, eq(nm)))
[=] join(get_items(root, "x"))
```

Let me know if that works for you.

**Comment by sswatson** [comment]
Yes, that works great, thanks. I wasn't alert to the possibility of `flatten`, and that makes things easy.
