### ISSUE TITLE
Referencing current item

### ISSUE THREAD

**Issue by sswatson** [calculist/calculist#35]
I'm often interested in referencing the current item in a formula, e.g., for purposes of setting its value to some complicated function of its descendant tree. Currently I'm using `@item($guid)`, and actually that has worked well so far. But I'm just curious if there's a more idiomatic approach, because it feels like I probably stumbled upon a suboptimal solution. 

Here's a simplified example for concreteness. 

```
a [=] sum(flatten(@item($guid)))
  b [:] 3
    c [:] 7
    d [:] 5
  e [:] 1
```

**Comment by danallison** [comment]
I think what you're looking for is the `$items` variable, which is the array of sub-items of the current item. In your example, it would look like

```
a [=] sum(flatten($items))
  b [:] 3
    c [:] 7
    d [:] 5
  e [:] 1
```

**Comment by sswatson** [comment]
Cool, thanks.
