### ISSUE TITLE
Nice Printing Format

### ISSUE THREAD

**Issue by nkallman** [calculist/calculist#6]
If you include the following CSS in Calculist it would make the printing experience a lot better.
Since it already looks like a "page" in the display this will make it appear the same way on the page to be printed.

```
@media print {
    #header
    {
        display: none;
    }
    #main-container
    {
        padding: 0;
    }
    #main-container .main-page
    {
        margin: 0;
        padding: 20px;
    }
    #main-container .page
    {
        box-shadow: none;
        outline: none
    }
}
```

Thanks!

**Comment by danallison** [comment]
Deployed. Thank you.
